### ISSUE TITLE
[ERROR]  Trilium requires javascript to be enabled when trying to use this plugin

### ISSUE THREAD

**Issue by Greatz08** [soulsands/trilium-chat#21]
@soulsands  ![image](https://github.com/user-attachments/assets/4aa59434-b4e8-4f80-85b0-1ccbb71e233f)
Please guide what can be the cause of it and how can we fix it. I am currently using latest triliumnext latest version and this was my first time experience of using plugin in trilium.

**Comment by eliandoran** [comment]
@Greatz08 , the "Trilium requires JavaScript to be enabled" is not actually an error, it's just part of the Trilium HTML document structure. What you are looking for is the "Console" tab (see the tabs on the right side of the screen with "Elements", "Console", "Sources", etc.). There you should find the errors.

**Comment by Greatz08** [comment]
@eliandoran  thanks for responding back regarding my issue. I know its not typical error still it is kind of issue i am getting so thought to address it as error. I dont know why its giving me this issue since i have fresh installed it using docker compose method. This is my docker compose file:
```


services:
  trilium:
    image: triliumnext/notes:latest
    restart: unless-stopped
    ports:
      - "8044:8080"
    volumes:
      - ./trilium-data:/home/node/trilium-data
    container_name: trilliumnext
    
```

As you tested with chatgpt api key and it worked for you so maybe is it ollama related issue ? Can you please run  any small ollama model like phi3 or any other quantized version  if you dont have gpu or low power gpu like 1b or 3b models  will for sure run even if you might not have powerful gpu and then please try to connect and tell if it is working or not for you. Because i tried with ollama using - localhost:11434  path and tried with 127.0.0.1 too so yeah please try and tell if it works for you or not so that we can conclude if this issue is for me only (which shouldnt happen technically because i am using same docker image as you so it must be either configuration issue or this program might not be working for recent ollama version or something else which we need to understand and try to fix it.
